#!/bin/bash
# Daily Report - Generate daily summary for Timmy

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)

echo "📅 Daily Report - $DATE @ $TIME"
echo "================================"
echo ""

# Bob's stats
echo "🤖 Bob's Activity:"
echo "  Commits today: $(cd /home/timmy/.openclaw/workspace && git log --since="24 hours ago" --oneline 2>/dev/null | wc -l)"
echo "  Total commits: $(cd /home/timmy/.openclaw/workspace && git log --oneline 2>/dev/null | wc -l)"
echo "  Skills: $(ls /home/timmy/.openclaw/workspace/skills 2>/dev/null | wc -l)"
echo "  Scripts: $(ls /home/timmy/.openclaw/workspace/scripts/*.sh 2>/dev/null | wc -l)"
echo ""

# Project status
echo "📁 Active Projects:"
/home/timmy/.openclaw/workspace/skills/project-health-monitor/scripts/project-health.sh /home/timmy/encyphrix-pro 2>/dev/null | grep -E "(🟢|🟡|🔴)" | head -1
echo ""

# System health
echo "💾 System:"
echo "  Disk: $(df -h /home | tail -1 | awk '{print $5}') used"
echo "  Memory: $(free -h 2>/dev/null | grep Mem | awk '{print $3}' | tr -d 'Gi')GB used"
echo "  Load: $(uptime | awk -F'load average:' '{print $2}' | cut -d',' -f1)"
echo ""

# Pending items
echo "📝 Pending:"
echo "  Projects needing cleanup: $(/home/timmy/.openclaw/workspace/skills/project-health-monitor/scripts/project-health-all.sh /home/timmy 2>/dev/null | grep -E "🟡|🔴" | wc -l)"
echo ""

# Moltbook status
echo "🦞 Moltbook:"
echo "  Profile: https://www.moltbook.com/u/BobBuild"
echo "  Status: Verified ✅"
echo ""

echo "---"
echo "Generated by Bob 🤖"
echo "Next report: Tomorrow 9am"
