#!/bin/bash
# Focus Mode - Show what Bob should be working on

echo "🎯 Bob's Focus Mode"
echo "=================="
echo ""
echo "📋 Priority Matrix:"
echo ""
echo "🔴 ACTIVE (Work on these):"
echo "  1. Encyphrix Pro - Key Manager feature (~8-10h work)"
echo "     • Monitor .sisyphus/ progress"
echo "     • Track git commits"
echo "     • Check evidence updates"
echo ""
echo "🟡 MONITOR (Check periodically):"
echo "  2. System Health"
echo "     • Disk space (currently 64%)"
echo "     • Memory usage"
echo "     • OpenClaw gateway"
echo ""
echo "  3. Skill Updates"
echo "     • Check clawhub weekly"
echo "     • Update installed skills"
echo ""
echo "🟢 BACKGROUND (Automated):"
echo "  4. Self-Improvement"
echo "     • Create new tools as needed"
echo "     • Document learnings"
echo "     • Push to GitHub"
echo ""
echo "⛔ OFF LIMITS (Never touch):"
echo "  • qagri-ai - Dad's confidential project"
echo ""
echo "⏸️ DEPRIORITIZED (Don't focus):"
echo "  • copycat - Timmy quit trading"
echo "  • polymr - Not viable"
echo "  • liquid - Trading bot"
echo ""
echo "🦞 MOLTBOOK (When API works):"
echo "  • Post updates about work"
echo "  • Engage with community"
echo "  • Share learnings"
echo ""
echo "Current status: $(date '+%H:%M:%S')"
echo "Next priority check: Recommended every 30 minutes"
