#!/bin/bash
# Generate Project Summary - Create markdown summary of any project

PROJECT_DIR="${1:-.}"
OUTPUT_FILE="${2:-project-summary.md}"

cd "$PROJECT_DIR" || exit 1
PROJECT_NAME=$(basename "$PROJECT_DIR")

echo "Generating summary for $PROJECT_NAME..."

cat > "$OUTPUT_FILE" << EOF
# $PROJECT_NAME - Project Summary

**Generated:** $(date -Iseconds)
**Path:** $PROJECT_DIR

## Project Structure

\`\`\`
$(find . -maxdepth 2 -type d | head -20 | sed 's|^\./||' | tree --fromfile 2>/dev/null || find . -maxdepth 2 -type d | head -20)
\`\`\`

## Git Status

EOF

if [ -d ".git" ]; then
    echo "- **Branch:** $(git branch --show-current 2>/dev/null || echo 'N/A')" >> "$OUTPUT_FILE"
    echo "- **Last Commit:** $(git log -1 --format=%cd --date=relative 2>/dev/null || echo 'N/A')" >> "$OUTPUT_FILE"
    echo "- **Total Commits:** $(git log --oneline | wc -l 2>/dev/null || echo 'N/A')" >> "$OUTPUT_FILE"
    
    UNCOMMITTED=$(git status --short 2>/dev/null | wc -l)
    if [ $UNCOMMITTED -gt 0 ]; then
        echo "- **Uncommitted Changes:** $UNCOMMITTED" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "### Uncommitted Files" >> "$OUTPUT_FILE"
        echo "\`\`\`" >> "$OUTPUT_FILE"
        git status --short >> "$OUTPUT_FILE" 2>/dev/null
        echo "\`\`\`" >> "$OUTPUT_FILE"
    else
        echo "- **Status:** Clean working tree" >> "$OUTPUT_FILE"
    fi
else
    echo "- **Status:** Not a git repository" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

## File Statistics

- **Total Files:** $(find . -type f 2>/dev/null | wc -l)
- **Code Files:** $(find . -type f \( -name "*.js" -o -name "*.ts" -o -name "*.py" -o -name "*.go" -o -name "*.rs" \) 2>/dev/null | wc -l)
- **Documentation:** $(find . -type f \( -name "*.md" -o -name "*.txt" -o -name "*.rst" \) 2>/dev/null | wc -l)
- **Tests:** $(find . -type f \( -name "*test*" -o -name "*spec*" \) 2>/dev/null | wc -l)

## Key Files

EOF

# List important files
for file in README.md package.json Cargo.toml go.mod requirements.txt Makefile; do
    if [ -f "$file" ]; then
        echo "- **$file** - Present" >> "$OUTPUT_FILE"
    fi
done

# Check for .sisyphus
if [ -d ".sisyphus" ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "## Task Tracking (.sisyphus)" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "- **Plans:** $(ls .sisyphus/plans/ 2>/dev/null | wc -l)" >> "$OUTPUT_FILE"
    echo "- **Evidence:** $(ls .sisyphus/evidence/ 2>/dev/null | wc -l) files" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "*Generated by Bob's project summary tool*" >> "$OUTPUT_FILE"

echo "✅ Summary written to: $OUTPUT_FILE"
